sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
  - oraclejdk8
  - oraclejdk11
  - oraclejdk-ea
cache:
    apt: true
    directories:
        - $HOME/.m2
script: xvfb-run mvn install -Pjacoco coveralls:report
before_install:
  - sudo apt install -y xvfb
  - "export DISPLAY=:99.0"
addons:
  apt:
    update: true
