sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
  - oraclejdk8
  - oraclejdk11
  - oraclejdk-ea
cache:
    apt: true
    directories:
        - $HOME/.m2
script: mvn install -Pjacoco coveralls:report
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
